[package]
name = "raytracer4d-rs"
version = "0.1.0"
authors = ["Just-a-Nibble"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
